apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptime-pvc
  namespace: {{ .Release.Namespace}}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}