{
 "title": "demo-app",
 "time": { "from": "2026-10-08T12:13:11.741Z", "to": "2026-10-08T12:42:00.434Z" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{namespace=\"demo-app\", handler=\"/\"}[1m]))",
     "legendFormat": "toplam"
    }
   ]
  },
  {
   "title": "Latency p95 (/slow)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95,\r\n  sum by (le) (rate(http_request_duration_seconds_bucket{namespace=\"demo-app\", handler=\"/slow\"}[5m]))\r\n)",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 19, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{namespace=\"demo-app\", status=\"5xx\"} [1m]))\r\n/\r\nsum(rate(http_requests_total{namespace=\"demo-app\", } [1m]))",
     "legendFormat": "hata oranı"
    }
   ]
  }
 ]
}