apiVersion: v1
kind: Service
metadata:
  name: it-tool
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: it-tool
  ports:
    - port: 80
      targetPort: 80
      
      